default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DB_USERNAME'] || 'postgres' %>
  password: <%= ENV['DB_PASSWORD'] || 'password' %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: <%= ENV['DB_NAME_DEVELOPMENT'] || 'backend_development' %>

test:
  <<: *default
  database: <%= ENV['DB_NAME_TEST'] || 'backend_test' %>

production:
  <<: *default
  database: <%= ENV['DB_NAME_PRODUCTION'] || 'backend_production' %>
  username: <%= ENV['DB_USERNAME_PRODUCTION'] || 'backend' %>
  password: <%= ENV['DB_PASSWORD_PRODUCTION'] %>
