default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  host: db #デフォルトでは無いので設定

development:
  <<: *default
  database: backend_development #適宜修正

test:
  <<: *default
  database: backend_test #適宜修正

production:
  <<: *default
  database: backend_production #適宜修正
  username: backend #適宜修正
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %> #適宜修正
