# この設定ファイルは `rubocop --auto-gen-config` によって生成されました
# 2024-03-15 09:24:46 UTC に RuboCop バージョン 1.62.1 を使用して生成されました。
# このファイルの設定は、コードベースから違反が取り除かれるごとに削除していくことを目的としています。
# 検査対象のコードに変更が加えられたり、新しいバージョンの RuboCop をインストールすると、このファイルを再生成する必要があるかもしれません。

# 違反数: 1
# 設定パラメータ: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
# AllowedMethods: refine
Metrics/BlockLength:
  Max: 48 # ブロックの最大行数を48に設定

# 違反数: 1
# 設定パラメータ: CountComments, CountAsOne, AllowedMethods, AllowedPatterns.
Metrics/MethodLength:
  Max: 14 # メソッドの最大行数を14に設定

Metrics/ClassLength:
  Max: 120

# 違反数: 11
# 設定パラメータ: AllowedConstants.
Style/Documentation:
  Exclude:
    - "spec/**/*" # RSpecのファイルは除外
    - "test/**/*" # テストファイルは除外
    - "app/mailers/application_mailer.rb" # メーラーは除外
    - "app/models/application_record.rb" # モデルのベースクラスは除外
    - "app/models/like.rb" # モデルは除外
    - "app/models/post.rb" # モデルは除外
    - "app/models/relationship.rb" # モデルは除外
    - "app/models/user.rb" # モデルは除外
    - "config/application.rb" # アプリケーション設定ファイルは除外

# 違反数: 39
# このコップは安全でない自動修正 (--autocorrect-all) をサポートしています。
# 設定パラメータ: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false # フローズン文字列リテラルコメントの強制を無効化

# 違反数: 1
# このコップは安全でない自動修正 (--autocorrect-all) をサポートしています。
Style/GlobalStdStream:
  Exclude:
    - "config/environments/production.rb" # プロダクション環境設定ファイルは除外

# 違反数: 2
# このコップは安全でない自動修正 (--autocorrect-all) をサポートしています。
# 設定パラメータ: SafeForConstants.
Style/RedundantFetchBlock:
  Exclude:
    - "config/puma.rb" # Puma設定ファイルは除外
