inherit_from: .rubocop_todo.yml

require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb" # スキーマファイルは自動生成されるため除外
    - "bin/*" # ビンスクリプトは除外
    - "node_modules/**/*" # フロントエンド依存関係は除外
    - "vendor/**/*" # サードパーティのソースコードは除外
    - "spec/**/*"

# Rails固有のコーディングスタイルを適用
Rails:
  Enabled: true

# メトリクス（長さや複雑さに関するルール）の調整
Metrics/BlockLength:
  Exclude:
    - "config/environments/*.rb" # 環境設定ファイルは除外
    - "config/routes.rb" # ルーティングファイルは除外
    - "spec/**/*.rb" # RSpecのファイルは除外
Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb
  Max: 15 # メソッドの最大行数を15に設定
Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb

# ドキュメンテーションコメントの強制を無効化
Style/Documentation:
  Enabled: false

# 文字列リテラルの引用符のスタイル（デフォルトはシングルクォートを推奨）
Style/StringLiterals:
  EnforcedStyle: single_quotes

# その他のカスタム設定...
Layout/LineLength:
  Max: 160

Rails/BulkChangeTable:
  Exclude:
    - db/migrate/20240317233629_remove_auth_columns_from_users.rb
