services:
  # Rails バックエンドのサービス設定
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "3001:3000"
    environment:
      - TZ=Asia/Tokyo
  # React フロントエンドのサービス設定
  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - TZ=Asia/Tokyo
