services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Tokyo
      POSTGRES_USER: app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_test
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
      - bundle_data:/usr/local/bundle:cached
      - node_modules:/app/node_modules
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH}
    command: ["http", "web:3000"]
    depends_on:
      - web
    ports:
      - "4040:4040"

volumes:
  postgres_data:
  bundle_data:
  node_modules:
