version: '3.8'
services:
  db:
    image: postgres
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build: ./docker/rails
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/backend
      - bundle_data:/usr/local/bundle
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend  # ビルドコンテキストをfrontendディレクトリに設定
      dockerfile: ../docker/react/Dockerfile  # docker/reactディレクトリ内のDockerfileを指定
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    environment:
      NODE_ENV: development
    ports:
      - "3001:3000"
    restart: always

volumes:
  bundle_data:
  node_modules:
  postgres_volume:
    external: true
