services:
  backend:
    volumes:
      - ./backend:/app # ローカルの変更をコンテナにリアルタイムで反映
    environment:
      - RAILS_ENV=development

  frontend:
    volumes:
      - ./frontend:/app # ローカルの変更をコンテナにリアルタイムで反映
    environment:
      - NODE_ENV=development
