version: '3.8'
services:
  db:
    image: postgres:16.2
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ../docker/rails/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./backend:/backend
      - bundle_data:/usr/local/bundle
      - postgres_volume:/var/lib/postgresql/data
    environment:
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/react/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: npm start
    environment:
      NODE_ENV: development
    ports:
      - "3001:3000"
    restart: always

volumes:
  bundle_data:
  node_modules:
  postgres_volume:
