databases:
  - name: WaveConGra
    databaseName: dbcongra
    user: shonosuke
    region: singapore

services:
  - type: web
    name: WaveConGra
    runtime: ruby
    region: singapore
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: WaveConGra
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
      - key: REDIS_URL
        fromService:
          name: Gmail通知
          property: redisUrl

  - type: redis
    name: Gmail通知
    plan: free
    region: singapore
    maxmemoryPolicy: noeviction
    ipAllowList: []
