databases:
  - name: gratiwave_DB
    databaseName: gratiwave_db
    user: shonosuke
    region: singapore

services:
  - type: web
    name: gratiwave_db
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gratiwave_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
