services:
  - type: redis
    name: Gmail通知
    region: singapore
    maxmemoryPolicy: allkeys-lru
    plan: free

  - type: worker
    name: sidekiq-worker
    runtime: ruby
    region: singapore
    buildCommand: bundle install
    startCommand: bundle exec sidekiq -C config/sidekiq.yml
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: Gmail通知
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

  - type: web
    name: WaveConGra
    runtime: ruby
    region: singapore
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: WaveConGra
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: Gmail通知
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2
