default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: <%= ENV.fetch("POSTGRES_PASSWORD") %>
  port: 5432
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gratiwave_development

test:
  <<: *default
  database: gratiwave_test

production:
  <<: *default
  database: gratiwave_production
  username: gratiwave
  password: <%= ENV["GRATIWAVE_DATABASE_PASSWORD"] %>
