default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: app
  password: password
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  <<: *default
  database: app_production
  url: <%= ENV['DATABASE_URL'] %>
