# ワークフローの名前
name: Rails CI

# このワークフローが実行されるトリガー
on: [push]

jobs:
  # バックエンドのテストジョブ
  app-tests:
    # 実行環境をUbuntuの最新版に設定
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
          POSTGRES_HOST_AUTH_METHOD: md5
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # 実行するステップ
    steps:
      - uses: actions/checkout@v4 # リポジトリのチェックアウト

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Rubyのセットアップ
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3.0"
          bundler-cache: true

      - name: Build CSS
        run: |
          bundle exec rails css:build

      # データベースのセットアップ
      - name: Setup database
        run: |
          docker compose -f compose.test.yml run --rm web bundle exec rails db:create RAILS_ENV=test
          docker compose -f compose.test.yml run --rm web bundle exec rails db:migrate RAILS_ENV=test
        env:
          RAILS_ENV: test
        working-directory: .

      # Rubocopでコードの静的解析
      - name: Run RuboCop
        run: docker compose -f compose.test.yml run --rm web bundle exec rubocop
        env:
          RAILS_ENV: test
        working-directory: .
